swagger: '2.0'
info:
  version: ''
  title: Tax Classes
  description: >-
    ### Tax Class


    The Tax Class object, and endpoints, manage tax calculations applied to
    sales. Tax classes are used to apply different tax rates for specific types
    of products and orders. This API is read only. Classes must be set using the
    [Control Panel](https://forum.bigcommerce.com/s/article/Taxes-Video#).
host: api.bigcommerce.com
basePath: '/stores/{$$.env.store_hash}/v2'
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /tax_classes:
    get:
      description: |-
        Returns a list of all *Tax Classes* in a store.

        Default sorting is by tax-class id, from lowest to highest.
      summary: Get All Tax Classes
      tags:
        - Taxes
      produces:
        - application/json
      parameters:
        - name: Accept
          in: header
          required: true
          type: string
          description: ''
          default: application/json
        - name: Content-Type
          in: header
          required: true
          type: string
          description: ''
          default: application/json
        - name: page
          in: query
          required: false
          type: number
          exclusiveMaximum: false
          exclusiveMinimum: false
          description: Optional filter param. Number of pages.
          maximum: 50
        - name: limit
          in: query
          required: false
          type: number
          exclusiveMaximum: false
          exclusiveMinimum: false
          description: Optional filter param. Number of items per page
          maximum: 250
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              title: Tax Class
              example:
                id: 1
                name: Shipping
              type: object
              properties:
                id:
                  description: >-
                    The unique numerical ID of the tax class. A read-only value
                    which is automatically assigned and increments sequentially.
                  example: 1
                  type: string
                name:
                  description: The name of the tax class.
                  example: Shipping
                  type: string
          examples:
            application/json:
              - id: 1
                name: Non-Taxable Products
              - id: 2
                name: Shipping
              - id: 3
                name: Gift Wrapping
            Response Schema:
              - id: proident irure consequat anim
                name: sed non commodo et tempor
              - id: consequat voluptate
                name: sunt ex
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
      operationId: getAllTaxClasses
  '/tax_classes/{id}':
    get:
      description: Returns a single *Tax Class*.
      summary: Get a Tax Class
      tags:
        - Taxes
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          description: Id of the tax class.
        - name: Accept
          in: header
          required: true
          type: string
          description: ''
        - name: Content-Type
          in: header
          required: true
          type: string
          description: ''
      responses:
        '200':
          description: ''
          schema:
            title: Tax Class
            example:
              id: 1
              name: Shipping
            type: object
            properties:
              id:
                description: >-
                  The unique numerical ID of the tax class. A read-only value
                  which is automatically assigned and increments sequentially.
                example: 1
                type: string
              name:
                description: The name of the tax class.
                example: Shipping
                type: string
          examples:
            application/json:
              id: 1
              name: Shipping
            Response Schema:
              id: ut pariatur eiusmod non
              name: dolore nulla Duis Ut ea
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
      operationId: getATaxClass
definitions:
  TaxClass:
    title: Tax Class
    example:
      id: 1
      name: Shipping
    type: object
    properties:
      id:
        description: >-
          The unique numerical ID of the tax class. A read-only value which is
          automatically assigned and increments sequentially.
        example: 1
        type: string
      name:
        description: The name of the tax class.
        example: Shipping
        type: string
tags:
  - name: Taxes
securityDefinitions:
  X-Auth-Client:
    type: apiKey
    name: X-Auth-Client
    in: header
    description: >-
      ### OAuth Scopes

      |  **UI Name** | **Permission** | **Parameter** |

      | --- | --- | --- |

      |  Information & Settings | modify | `store_v2_information` |

      |  Information & Settings | read-only | `store_v2_information_read_only` |


      ### Headers


      |Header|Parameter|Description|

      |-|-|-|

      |`X-Auth-Client`|`client_id`|Obtained by creating an API account or
      installing an app in a BigCommerce control panel.|

      |`X-Auth-Token`|`access_token `|Obtained by creating an API account or
      installing an app in a BigCommerce control panel.|


      ### Example


      ```http

      GET /stores/{$$.env.store_hash}/v3/catalog/summary

      host: api.bigcommerce.com

      Content-Type: application/json

      X-Auth-Client: {client_id}

      X-Auth-Token: {access_token}

      ```


      * For more information on Authenticating BigCommerce APIs, see:
      [Authentication](https://developer.bigcommerce.com/api-docs/getting-started/authentication). 
  X-Auth-Token:
    type: apiKey
    name: X-Auth-Token
    in: header
    description: >-
      ### OAuth Scopes

      |  **UI Name** | **Permission** | **Parameter** |

      | --- | --- | --- |

      |  Information & Settings | modify | `store_v2_information` |

      |  Information & Settings | read-only | `store_v2_information_read_only` |


      ### Headers


      |Header|Parameter|Description|

      |-|-|-|

      |`X-Auth-Client`|`client_id`|Obtained by creating an API account or
      installing an app in a BigCommerce control panel.|

      |`X-Auth-Token`|`access_token `|Obtained by creating an API account or
      installing an app in a BigCommerce control panel.|


      ### Example


      ```http

      GET /stores/{$$.env.store_hash}/v3/catalog/summary

      host: api.bigcommerce.com

      Content-Type: application/json

      X-Auth-Client: {client_id}

      X-Auth-Token: {access_token}

      ```


      * For more information on Authenticating BigCommerce APIs, see:
      [Authentication](https://developer.bigcommerce.com/api-docs/getting-started/authentication). 
security:
  - X-Auth-Client: []
  - X-Auth-Token: []
x-stoplight:
  docs:
    includeDownloadLink: true
    showModels: false
