swagger: '2.0'
info:
  version: ''
  title: Geography
  description: >-

    - [OAuth Scopes](#oauth-scopes)

    - [Authentication](#authentication)

    - [Available Endpoints](#available-endpoints)


    Introduction


    ## OAuth Scopes

    | UI Name                                      | Permission |
    Parameter                                     |

    |----------------------------------------------|------------|-----------------------------------------------|

    | Information & Settings                       | modify     |
    `store_v2_information`                        |

    | Information & Settings                       | read-only  |
    `store_v2_information_read_only`              |


    For more information on OAuth Scopes, see:
    [Authentication](https://developer.bigcommerce.com/api-docs/getting-started/authentication).


    ## Authentication


    Requests can be authenticated by sending a `client_id` and `access_token`
    via `X-Auth-Client` and `X-Auth-Token` HTTP headers:


    ```http

    GET /stores/{$$.env.store_hash}/v3/catalog/summary

    host: api.bigcommerce.com

    Accept: application/json

    X-Auth-Client: {client_id}

    X-Auth-Token: {access_token}

    ```


    |Header|Parameter|Description|

    |-|-|-|

    |`X-Auth-Client`|`client_id`|Obtained by creating an API account or
    installing an app in a BigCommerce control panel.|

    |`X-Auth-Token`|`access_token `|Obtained by creating an API account or
    installing an app in a BigCommerce control panel.|


    For more information on Authenticating BigCommerce APIs, see:
    [Authentication](https://developer.bigcommerce.com/api-docs/getting-started/authentication).


    ## Available Endpoints

    |
    Resource                                                                                             
    | Description                      |

    |-------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------|

    |
    [Countries](https://developer.bigcommerce.com/api-reference/store-management/geography-api/countries)
    | A country or territory, identifiable by an ISO 3166 country
    code.                                              |

    |
    [States](https://developer.bigcommerce.com/api-reference/store-management/geography-api/states)      
    | A state or province, identifiable by an [ISO
    3166](https://en.wikipedia.org/wiki/ISO_3166-2) subdivision code. |
host: api.bigcommerce.com
basePath: '/stores/{$$.env.store_hash}/v2'
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /countries:
    get:
      description: >-
        Get a list of all countries available. A country or territory,
        identifiable by an ISO 3166 country code.
      summary: Get all Countries
      parameters:
        - name: Accept
          in: header
          required: true
          type: string
          description: ''
          default: application/json
        - name: Content-Type
          in: header
          required: true
          type: string
          description: ''
          default: application/json
        - name: page
          in: query
          required: false
          type: number
          exclusiveMaximum: false
          exclusiveMinimum: false
          description: Number of pages
        - name: limit
          in: query
          required: false
          type: number
          exclusiveMaximum: false
          exclusiveMinimum: false
          description: Count per page
        - in: query
          name: country
          type: string
        - in: query
          name: country_iso2
          type: string
        - in: query
          name: country_iso3
          type: string
      responses:
        '200':
          $ref: '#/responses/countriesCollectionResponse'
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
      tags:
        - Countries
  '/countries/{id}':
    get:
      description: >-
        Returns a single *Country*. 


        Gets a country. A country or territory, identifiable by an ISO 3166
        country code.
      summary: Get a Country
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          exclusiveMaximum: false
          exclusiveMinimum: false
          description: The id of the country.
        - name: Accept
          in: header
          required: true
          type: string
          description: ''
          default: application/json
        - name: Content-Type
          in: header
          required: true
          type: string
          description: ''
          default: application/json
      responses:
        '200':
          $ref: '#/responses/countriesResponse'
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
      tags:
        - Countries
    parameters:
      - name: id
        in: path
        type: string
        required: true
  '/countries/{country_id}/states':
    get:
      description: |-
        Returns a list of *States* belonging to a *Country*. 

        A state or province, identifiable by an ISO 3166 subdivision code.
      summary: Get All Country's States
      parameters:
        - name: country_id
          in: path
          required: true
          type: integer
          exclusiveMaximum: false
          exclusiveMinimum: false
          description: Id of the country
        - name: Accept
          in: header
          required: true
          type: string
          description: ''
        - name: Content-Type
          in: header
          required: true
          type: string
          description: ''
        - name: state
          in: query
          required: false
          type: string
          description: Name of the state/province.
        - name: state_abbreviation
          in: query
          required: false
          type: string
          description: Abbreviation for the state/province.
        - name: page
          in: query
          required: false
          type: number
          exclusiveMaximum: false
          exclusiveMinimum: false
          description: Number of pages
        - name: limit
          in: query
          required: false
          type: number
          exclusiveMaximum: false
          exclusiveMinimum: false
          description: Count per page
      responses:
        '200':
          $ref: '#/responses/countriesStatesCollectionResponse'
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
      tags:
        - States
    parameters:
      - name: country_id
        in: path
        type: string
        required: true
  '/countries/{country_id}/states{id}':
    get:
      description: |-
        Returns a *State*. 

        A state or province, identifiable by an ISO 3166 subdivision code.
      summary: Get a Country's State
      produces:
        - application/json
      parameters:
        - name: country_id
          in: path
          required: true
          type: integer
          exclusiveMaximum: false
          exclusiveMinimum: false
          description: Id of the country
        - name: id
          in: path
          required: true
          type: integer
          exclusiveMaximum: false
          exclusiveMinimum: false
          description: Id of the states
        - name: Accept
          in: header
          required: true
          type: string
          description: ''
          default: application/json
        - name: Content-Type
          in: header
          required: true
          type: string
          description: ''
          default: application/json
      responses:
        '200':
          $ref: '#/responses/countriesStatesResponse'
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
      tags:
        - States
    parameters:
      - name: country_id
        in: path
        type: string
        required: true
      - name: id
        in: path
        type: string
        required: true
  /countries/count:
    get:
      responses:
        '200':
          $ref: '#/responses/countResponse'
      summary: Get Count of All Contries
      tags:
        - Countries
      operationId: countriesCount
      description: Returns a count of all countries.
  /countries/states/count:
    get:
      responses:
        '200':
          $ref: '#/responses/countResponse'
      summary: Get Count of All States
      tags:
        - States
      description: Returns a count of all states.
  /countries/states:
    get:
      responses:
        '200':
          $ref: '#/responses/countriesStatesCollectionResponse'
      summary: Get all States
      tags:
        - States
      description: Returns a list of all states.
  '/countries/{country_id}/states/count':
    get:
      responses:
        '200':
          $ref: '#/responses/countResponse'
      summary: Get a County's States Count
      tags:
        - States
      description: Returns a count of a country's states.
    parameters:
      - name: country_id
        in: path
        type: string
        required: true
definitions:
  country_Full:
    title: country_Full
    example:
      id: 13
      country: Australia
      country_iso2: AU
      country_iso3: AUS
      states:
        url: >-
          https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/13/states
        resource: /countries/13/states
    type: object
    properties:
      id:
        description: Id of the country.
        example: 13
        type: integer
      country:
        description: Country name.
        example: Australia
        type: string
      country_iso2:
        description: 2-letter country code.
        example: AU
        type: string
      country_iso3:
        description: 3-letter country code.
        example: AUS
        type: string
      states:
        $ref: '#/definitions/countriesStates_Full'
  countriesStates_Full:
    title: countriesStates_Full
    type: object
    properties:
      url:
        description: ''
        example: >-
          https://api.bigcommerce.com/stores/{$$.env.store_hash}/v2/countries/13/states
        type: string
      resource:
        description: ''
        example: /countries/13/states
        type: string
    description: Refers to the `states` object return in `GET` countries requests.
  countriesState_Full:
    title: countriesState_Full
    example:
      id: 208
      state: Australian Capital Territory
      state_abbreviation: ACT
      country_id: 13
    type: object
    properties:
      id:
        description: Numeric ID of the state/province.
        example: 208
        type: integer
      state:
        description: Name of the state/province.
        example: Australian Capital Territory
        type: string
      state_abbreviation:
        description: Abbreviation for the state/province.
        example: ACT
        type: string
      country_id:
        description: Numeric ID of the state’s/province’s associated country.
        example: 13
        type: integer
    description: 'Refers to the state returned in `GET` states requests. '
  countries_Resp:
    type: object
    properties: {}
  count_Full:
    type: object
    properties:
      count:
        type: integer
        minimum: 1
securityDefinitions:
  X-Auth-Token:
    type: apiKey
    name: X-Auth-Token
    in: header
    description: >-
      ### OAuth Scopes

      |  **UI Name** | **Permission** | **Parameter** |

      | --- | --- | --- |

      |  Information & Settings | modify | `store_v2_information` |

      |  Information & Settings | read-only | `store_v2_information_read_only` |


      ### Headers


      |Header|Parameter|Description|

      |-|-|-|

      |`X-Auth-Client`|`client_id`|Obtained by creating an API account or
      installing an app in a BigCommerce control panel.|

      |`X-Auth-Token`|`access_token `|Obtained by creating an API account or
      installing an app in a BigCommerce control panel.|


      ### Example


      ```http

      GET /stores/{$$.env.store_hash}/v3/catalog/summary

      host: api.bigcommerce.com

      Content-Type: application/json

      X-Auth-Client: {client_id}

      X-Auth-Token: {access_token}

      ```


      * For more information on Authenticating BigCommerce APIs, see:
      [Authentication](https://developer.bigcommerce.com/api-docs/getting-started/authentication). 
  X-Auth-Client:
    type: apiKey
    name: X-Auth-Client
    in: header
    description: >-
      ### OAuth Scopes

      |  **UI Name** | **Permission** | **Parameter** |

      | --- | --- | --- |

      |  Information & Settings | modify | `store_v2_information` |

      |  Information & Settings | read-only | `store_v2_information_read_only` |


      ### Headers


      |Header|Parameter|Description|

      |-|-|-|

      |`X-Auth-Client`|`client_id`|Obtained by creating an API account or
      installing an app in a BigCommerce control panel.|

      |`X-Auth-Token`|`access_token `|Obtained by creating an API account or
      installing an app in a BigCommerce control panel.|


      ### Example


      ```http

      GET /stores/{$$.env.store_hash}/v3/catalog/summary

      host: api.bigcommerce.com

      Content-Type: application/json

      X-Auth-Client: {client_id}

      X-Auth-Token: {access_token}

      ```


      * For more information on Authenticating BigCommerce APIs, see:
      [Authentication](https://developer.bigcommerce.com/api-docs/getting-started/authentication). 
security:
  - X-Auth-Token: []
  - X-Auth-Client: []
tags:
  - name: Countries
  - name: States
x-stoplight:
  docs:
    includeDownloadLink: true
    showModels: false
responses:
  countriesResponse:
    description: ''
    schema:
      $ref: '#/definitions/country_Full'
    examples:
      application/json:
        id: 1
        country: Afghanistan
        country_iso2: AF
        country_iso3: AFG
        states:
          url: 'https://api.bigcommerce.com/stores/h10wocxy6s/v2/countries/1/states'
          resource: /countries/1/states
  countriesStatesResponse:
    description: ''
    schema:
      $ref: '#/definitions/countriesState_Full'
  countriesCollectionResponse:
    description: ''
    schema:
      type: array
      items:
        $ref: '#/definitions/country_Full'
    examples:
      application/json: |-
        [
          {
            "id": 1,
            "country": "Afghanistan",
            "country_iso2": "AF",
            "country_iso3": "AFG",
            "states": {
              "url": "https:\/\/api.bigcommerce.com\/stores\/store_hash\/v2\/countries\/1\/states",
              "resource": "\/countries\/1\/states"
            }
          },
          {
            "id": 2,
            "country": "Albania",
            "country_iso2": "AL",
            "country_iso3": "ALB",
            "states": {
              "url": "https:\/\/api.bigcommerce.com\/stores\/store_hash\/v2\/countries\/2\/states",
              "resource": "\/countries\/2\/states"
            }
          },
          // ...
          ]
  countriesStatesCollectionResponse:
    description: ''
    schema:
      type: object
      properties: {}
  countResponse:
    description: ''
    schema:
      $ref: '#/definitions/count_Full'
    examples:
      application/json:
        count: 241
