swagger: '2.0'
info:
  version: ''
  title: Payment Methods
  description: >-
    Returns a list of all enabled *Payment Methods* on a store.

    If you are trying to process payment for an order see [Payments
    API](/api-docs/payments/payments-api-overview).
  termsOfService: ''
  license:
    name: ''
host: api.bigcommerce.com
basePath: '/stores/{$$.env.store_hash}/v2'
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /payments/methods:
    get:
      description: >-
        Gets the list of enabled payment methods. Default sorting is by payment
        method, alphabetically from A to Z.
      summary: Get All Payment Methods
      parameters:
        - name: Accept
          in: header
          required: true
          type: string
          description: ''
          default: application/json
        - name: Content-Type
          in: header
          required: true
          type: string
          description: ''
          default: application/json
        - name: page
          in: query
          required: false
          type: number
          exclusiveMaximum: false
          exclusiveMinimum: false
          description: 'Optional filter param `/api/v2/payments/methods?page={number}`'
        - name: limit
          in: query
          required: false
          type: number
          exclusiveMaximum: false
          exclusiveMinimum: false
          description: 'Optional filter param `/api/v2/payments/methods?limit={count}`'
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              title: PaymentMethod
              example:
                code: squarev2
                name: Square
                test_mode: false
              type: object
              properties:
                code:
                  description: Unique platform-wide code identifying the payment method.
                  example: squarev2
                  type: string
                name:
                  description: Descriptive name of the payment method.
                  example: Square
                  type: string
                test_mode:
                  description: >-
                    Determines whether the payment gateway is in test mode.
                    Always false for offline payment methods.
                  example: false
                  type: boolean
          examples:
            application/json:
              - code: braintree
                name: Braintree
                test_mode: false
              - code: braintreepaypal
                name: Braintree (PayPal)
                test_mode: false
              - code: braintreepaypalcredit
                name: Braintree (PayPal Credit)
                test_mode: false
              - code: instore
                name: Pay in Store
                test_mode: false
            Response Schema:
              - code: fugiat aliqua elit
                name: do consequat
                test_mode: true
              - code: quis
                name: dolor ad ut anim
                test_mode: false
              - code: nisi
                name: in deserunt in
                test_mode: true
              - code: ullamco est
                name: 'sit '
                test_mode: true
              - code: id ut sunt consequa
                name: cupidata
                test_mode: false
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
      tags:
        - Payment Methods
definitions:
  PaymentMethod:
    title: PaymentMethod
    example:
      code: squarev2
      name: Square
      test_mode: false
    type: object
    properties:
      code:
        description: Unique platform-wide code identifying the payment method.
        example: squarev2
        type: string
      name:
        description: Descriptive name of the payment method.
        example: Square
        type: string
      test_mode:
        description: >-
          Determines whether the payment gateway is in test mode. Always false
          for offline payment methods.
        example: false
        type: boolean
tags:
  - name: Payment Methods
securityDefinitions:
  X-Auth-Client:
    type: apiKey
    name: X-Auth-Client
    in: header
    description: >-
      ### OAuth Scopes

      |  **UI Name** | **Permission** | **Parameter** |

      | --- | --- | --- |

      |  Get Payment Methods | read-only | `store_payments_methods_read` |


      ### Headers


      |Header|Parameter|Description|

      |-|-|-|

      |`X-Auth-Client`|`client_id`|Obtained by creating an API account or
      installing an app in a BigCommerce control panel.|

      |`X-Auth-Token`|`access_token `|Obtained by creating an API account or
      installing an app in a BigCommerce control panel.|


      ### Example


      ```http

      GET /stores/{$$.env.store_hash}/v3/catalog/summary

      host: api.bigcommerce.com

      Content-Type: application/json

      X-Auth-Client: {client_id}

      X-Auth-Token: {access_token}

      ```


      * For more information on Authenticating BigCommerce APIs, see:
      [Authentication](https://developer.bigcommerce.com/api-docs/getting-started/authentication). 
  X-Auth-Token:
    type: apiKey
    name: X-Auth-Token
    in: header
    description: >-
      ### OAuth Scopes

      |  **UI Name** | **Permission** | **Parameter** |

      | --- | --- | --- |

      |  Get Payment Methods | read-only | `store_payments_methods_read` |


      ### Headers


      |Header|Parameter|Description|

      |-|-|-|

      |`X-Auth-Client`|`client_id`|Obtained by creating an API account or
      installing an app in a BigCommerce control panel.|

      |`X-Auth-Token`|`access_token `|Obtained by creating an API account or
      installing an app in a BigCommerce control panel.|


      ### Example


      ```http

      GET /stores/{$$.env.store_hash}/v3/catalog/summary

      host: api.bigcommerce.com

      Content-Type: application/json

      X-Auth-Client: {client_id}

      X-Auth-Token: {access_token}

      ```


      * For more information on Authenticating BigCommerce APIs, see:
      [Authentication](https://developer.bigcommerce.com/api-docs/getting-started/authentication). 
security:
  - X-Auth-Client: []
  - X-Auth-Token: []
x-stoplight:
  docs:
    includeDownloadLink: true
    showModels: false
