swagger: '2.0'
info:
  version: '1.0'
  title: Storefront Orders
  description: |-
    ## Storefront Orders API
    Returns order data immediately after an order is placed on the storefront.
  termsOfService: 'https://www.bigcommerce.com/terms/api-terms/'
host: '{$$.env.store_domain}'
basePath: /api/storefront
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  '/orders/{orderId}':
    get:
      description: >-
        Returns *Order* data. This will return order data immediately after an
        order is placed on the storefront.
      summary: Get Order
      tags:
        - Order
      operationId: OrdersByOrderIdGet
      produces:
        - application/json
      parameters:
        - name: orderId
          in: path
          required: true
          type: integer
          format: int32
          exclusiveMaximum: false
          exclusiveMinimum: false
          description: ID of an Order.
      responses:
        '200':
          $ref: '#/responses/order_Resp'
definitions:
  Data:
    title: Data
    description: >-
      Response data container for Order endpoints (`POST /order` and `POST
      /order/{orderId}`).
    type: object
    properties:
      order:
        $ref: '#/definitions/Order'
  Order:
    title: Order
    type: object
    properties:
      orderId:
        type: number
        description: ''
        format: double
        minimum: 1
        multipleOf: 1
      cartId:
        description: The Id of cart that was converted to order.
        type: string
        format: uuid
      currency:
        $ref: '#/definitions/Currency'
      isTaxIncluded:
        description: Whether this item is taxable.
        type: boolean
      baseAmount:
        description: 'Cost of cart''s contents, before applying discounts.'
        type: number
        format: double
      discountAmount:
        description: Discounted amount.
        type: number
        format: double
      orderAmount:
        description: >-
          Sum of line-items amounts, minus cart-level discounts and coupons.
          This amount includes taxes (where applicable).
        type: number
        format: double
      orderAmountAsInteger:
        description: Order amount represented in integer. Eg. 1234 for $12.34
        type: number
        format: double
      coupons:
        description: Array of `AppliedCoupon` objects applied to this cart.
        type: array
        items:
          $ref: '#/definitions/AppliedCoupon'
      lineItems:
        description: Array of `LineItem` objects.
        type: array
        items:
          $ref: '#/definitions/OrderLineItem'
      customerId:
        description: ''
        type: string
      token:
        description: ''
        type: string
      billingAddress:
        $ref: '#/definitions/AddressResponse'
      status:
        $ref: '#/definitions/Status'
      customerCreated:
        description: >-
          For guest checkouts, this flag will identify whether a new customer
          account was created for this order, or whether the billing email
          already existed on the store.
        type: boolean
      hasDigitalItems:
        description: Specifies whether this order has at least one digital item.
        type: boolean
      isDownloadable:
        description: >-
          Specifies whether this order is fully paid, so that digital items can
          be downloaded.
        type: boolean
      isComplete:
        description: >-
          Specifies whether this order is complete and ready to be taken to the
          order confirmation page.
        type: boolean
      customerMessage:
        description: Shopper's provided message for the order
        type: string
  Currency:
    title: Currency
    description: This will always be the same between cart and checkout.
    type: object
    properties:
      name:
        description: The currency name.
        type: string
      code:
        description: 'ISO-4217 currency code. (See: http://en.wikipedia.org/wiki/ISO_4217.)'
        type: string
      symbol:
        description: The currency symbol.
        type: string
      decimalPlaces:
        description: >-
          Number of decimal places for the currency. For example, USD currency
          has two decimal places.
        type: number
        format: double
  AppliedCoupon:
    title: Applied Coupon
    type: object
    properties:
      id:
        description: The coupon ID.
        type: string
      code:
        description: the coupon code
        type: string
      displayName:
        description: >-
          The coupon title based on different types provided in control panel
          section
        type: string
      couponType:
        description: Key name to identify the type of coupon.
        type: string
      discountedAmount:
        description: The discounted amount applied within a given context.
        type: number
        format: double
    required:
      - code
  AppliedDiscount:
    title: Applied Discount
    type: object
    properties:
      name:
        description: The name provided by the merchant.
        type: string
      discountedAmount:
        description: The discounted amount applied within a given context.
        type: number
        format: double
  OrderLineItem:
    title: Order Line Item
    type: object
    properties:
      physicalItems:
        description: Array of `ItemPhysical` objects.
        type: array
        items:
          $ref: '#/definitions/ItemPhysical'
      digitalItems:
        description: Array of `ItemDigital` objects.
        type: array
        items:
          $ref: '#/definitions/OrderItemDigital'
      giftCertificate:
        description: Array of `ItemGiftCertificate` objects.
        type: array
        items:
          $ref: '#/definitions/OrderItemGiftCertificate'
    required:
      - physicalItems
      - digitalItems
      - giftCertificate
  ItemPhysical:
    title: Item Physical
    type: object
    properties:
      id:
        description: The line-item ID.
        type: string
      parentId:
        description: Bundled items will have their parent's item Id.
        type: string
      variantId:
        description: ID of the variant.
        type: number
        format: double
      productId:
        description: ID of the product.
        type: number
        format: double
      sku:
        description: SKU of the variant.
        type: string
      name:
        description: The item's product name.
        type: string
      url:
        description: The product URL.
        type: string
      quantity:
        description: Quantity of this item.
        type: number
        format: double
      isTaxable:
        description: Whether the item is taxable.
        type: boolean
      imageUrl:
        description: 'URL of an image of this item, accessible on the internet.'
        type: string
      discounts:
        description: >-
          List of discounts applied to this item, as an array of AppliedDiscount
          objects.
        type: array
        items:
          $ref: '#/definitions/AppliedDiscount'
      discountAmount:
        description: >-
          The total value of all discounts applied to this item (excluding
          coupon).
        type: number
        format: double
      couponAmount:
        description: The total value of all coupons applied to this item.
        type: number
        format: double
      listPrice:
        description: 'Item''s list price, as quoted by the manufacturer/distributor.'
        type: number
        format: double
      salePrice:
        description: >-
          Item's price after all discounts are applied. (The final price before
          tax calculation.)
        type: number
        format: double
      extendedListPrice:
        description: Item's list price multiplied by the quantity.
        type: number
        format: double
      extendedSalePrice:
        description: Item's sale price multiplied by the quantity.
        type: number
        format: double
      type:
        description: the product type - physical or digital
        type: string
      addedByPromotion:
        description: Whether this item has been added automatically by a promotion.
        type: boolean
      isShippingRequired:
        description: Whether this item requires shipping to a physical address.
        type: boolean
      giftWrapping:
        $ref: '#/definitions/GiftWrapping'
      categories:
        type: array
        description: 'Categories the item belongs to. '
        items: {}
    required:
      - quantity
  GiftWrapping:
    title: Gift Wrapping
    type: object
    properties:
      name:
        description: ''
        type: string
      message:
        description: ''
        type: string
      amount:
        description: ''
        type: number
        format: double
  OrderItemDigital:
    title: Order Item Digital
    type: object
    properties:
      id:
        description: The line-item ID.
        type: string
      parentId:
        description: Bundled items will have their parent's item Id.
        type: string
      variantId:
        description: ID of the variant.
        type: number
        format: double
      productId:
        description: ID of the product.
        type: number
        format: double
      sku:
        description: SKU of the variant.
        type: string
      name:
        description: The item's product name.
        type: string
      url:
        description: The product URL.
        type: string
      quantity:
        description: Quantity of this item.
        type: number
        format: double
      isTaxable:
        description: Whether the item is taxable.
        type: boolean
      imageUrl:
        description: 'URL of an image of this item, accessible on the internet.'
        type: string
      discounts:
        description: >-
          List of discounts applied to this item, as an array of AppliedDiscount
          objects.
        type: array
        items:
          $ref: '#/definitions/AppliedDiscount'
      discountAmount:
        description: >-
          The total value of all discounts applied to this item (excluding
          coupon).
        type: number
        format: double
      couponAmount:
        description: The total value of all coupons applied to this item.
        type: number
        format: double
      listPrice:
        description: 'Item''s list price, as quoted by the manufacturer/distributor.'
        type: number
        format: double
      salePrice:
        description: >-
          Item's price after all discounts are applied. (The final price before
          tax calculation.)
        type: number
        format: double
      extendedListPrice:
        description: Item's list price multiplied by the quantity.
        type: number
        format: double
      extendedSalePrice:
        description: Item's sale price multiplied by the quantity.
        type: number
        format: double
      type:
        description: the product type - physical or digital
        type: string
      downloadFileUrls:
        description: URLs to download all product files.
        type: array
        items:
          type: string
      downloadPageUrl:
        description: The URL for the combined downloads page.
        type: string
      downloadSize:
        description: 'Combined download size, in human-readable style. E.g.: `30MB`.'
        type: string
      categories:
        type: array
        description: 'Categories the item belongs to. '
        items: {}
    required:
      - quantity
  OrderItemGiftCertificate:
    title: Order Item Gift Certificate
    type: object
    properties:
      name:
        description: The item's product name.
        type: string
      quantity:
        description: Quantity of this item.
        type: number
        format: double
      isTaxable:
        description: Whether the item is taxable.
        type: boolean
      amount:
        description: Price of the item
        type: number
        format: double
      type:
        description: Explicitly specifying the gift certificate type
        type: string
  AddressResponse:
    title: Address Response
    allOf:
      - $ref: '#/definitions/AddressProperties'
      - type: object
        properties:
          id:
            description: ''
            type: string
  AddressProperties:
    title: Address Properties
    type: object
    properties:
      firstName:
        description: ''
        type: string
      lastName:
        description: ''
        type: string
      email:
        description: ''
        type: string
      company:
        description: ''
        type: string
      address1:
        description: ''
        type: string
      address2:
        description: ''
        type: string
      city:
        description: ''
        type: string
      stateOrProvince:
        description: Represents state or province.
        type: string
      stateOrProvinceCode:
        description: ''
        type: string
      countryCode:
        description: >-
          ISO 3166-1 alpha-2 country code. (See:
          https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)
        type: string
      postalCode:
        description: ''
        type: string
      phone:
        description: ''
        type: string
        pattern: '^\+?[1-9]\d{1,14}(x\d{1-5})?$'
      customFields:
        description: ''
        type: array
        items:
          $ref: '#/definitions/CustomField'
    required:
      - countryCode
  CustomField:
    title: Custom Field
    type: object
    properties:
      fieldId:
        description: ''
        type: string
      fieldValue:
        description: >-
          This can also be an array for fields that need to support list of
          values (e.g., a set of check boxes.)
        type: string
  Status:
    title: Status
    description: Order status.
    example: INCOMPLETE
    type: string
    enum:
      - INCOMPLETE
      - PENDING
      - SHIPPED
      - PARTIALLY_SHIPPED
      - REFUNDED
      - CANCELLED
      - DECLINED
      - AWAITING_PAYMENT
      - AWAITING_PICKUP
      - AWAITING_SHIPMENT
      - COMPLETED
      - AWAITING_FULFILLMENT
      - MANUAL_VERIFICATION_REQUIRED
      - DISPUTED
      - PARTIALLY_REFUNDED
  BaseItem:
    title: Base Item
    type: object
    properties:
      id:
        description: The line-item ID.
        type: string
      parentId:
        description: Bundled items will have their parent's item Id.
        type: string
      variantId:
        description: ID of the variant.
        type: number
        format: double
      productId:
        description: ID of the product.
        type: number
        format: double
      sku:
        description: SKU of the variant.
        type: string
      name:
        description: The item's product name.
        type: string
      url:
        description: The product URL.
        type: string
      quantity:
        description: Quantity of this item.
        type: number
        format: double
      isTaxable:
        description: Whether the item is taxable.
        type: boolean
      imageUrl:
        description: 'URL of an image of this item, accessible on the internet.'
        type: string
      discounts:
        description: >-
          List of discounts applied to this item, as an array of AppliedDiscount
          objects.
        type: array
        items:
          $ref: '#/definitions/AppliedDiscount'
      discountAmount:
        description: >-
          The total value of all discounts applied to this item (excluding
          coupon).
        type: number
        format: double
      couponAmount:
        description: The total value of all coupons applied to this item.
        type: number
        format: double
      listPrice:
        description: 'Item''s list price, as quoted by the manufacturer/distributor.'
        type: number
        format: double
      salePrice:
        description: >-
          Item's price after all discounts are applied. (The final price before
          tax calculation.)
        type: number
        format: double
      extendedListPrice:
        description: Item's list price multiplied by the quantity.
        type: number
        format: double
      extendedSalePrice:
        description: Item's sale price multiplied by the quantity.
        type: number
        format: double
      type:
        description: the product type - physical or digital
        type: string
    required:
      - quantity
x-stoplight:
  docs:
    includeDownloadLink: true
    showModels: false
responses:
  order_Resp:
    description: ''
    schema:
      title: Response Order Data
      type: object
      properties:
        data:
          title: Data
          description: >-
            Response data container for Order endpoints (`POST /order` and `POST
            /order/{orderId}`).
          type: object
          properties:
            order:
              $ref: '#/definitions/Order'
        meta:
          description: ''
          type: object
          properties:
            '':
              type: string
