name: reviewdog
on: [pull_request]
# https://github.com/errata-ai/vale-action/blob/reviewdog/action.yml
jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@reviewdog
        with:
         reporter: github-pr-check
         filter_mode: added